[package]
name = "builtins"
version = "0.1.0"
authors = ["Nyrox <root@nyrox.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros={ path= "../macros"}
bytemuck="1.2"